name: Build PDF

on:
  push:
    branches: [ "main" ]
  pull_request:
  registry_package:
  workflow_dispatch:

jobs:
  build-pdf:
    name: Build PDF
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/moderncv/debian-texlive-docker:main

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build PDF
        run: latexmk -pdflatex='pdflatex -interaction=nonstopmode' -bibtex -pdf ./main.tex -outdir=build

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: main.pdf
          path: ./build/main.pdf

      # - name: Upload log
      #   if: ${{ always() }}
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: main.log
      #     path: ./build/main.log
